services:
  frontend:
    build:
      context: ./webapp
    container_name: financeModuleWebServer
    ports:
      - "80:80"

  backend:
    build:
      context: ./backend
    container_name: financeModuleBackend
    ports:
      - "5000:5000"   # example