services:
  frontend:
    build:
      context: ./webapp
    container_name: BridgePointWebServer
    ports:
      - "80:80"
    networks:
      - bridgepoint-network
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    container_name: BridgePointBackend
    ports:
      - "8000:8000"
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_NAME: bridgepointdb
      DB_USER: gm61admin
      DB_PASSWORD: camioninsta
    networks:
      - bridgepoint-network
    depends_on:
      - database

  database:
    build:
      context: ./database
    container_name: BridgePointDatabase
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: bridgepointdb
      POSTGRES_USER: gm61admin
      POSTGRES_PASSWORD: camioninsta
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - bridgepoint-network

volumes:
  data: {}

networks:
  bridgepoint-network:
    driver: bridge