services:
  frontend:
    build:
      context: ./webapp
    container_name: BridgePointWebServer
    ports:
      - "80:80"

  backend:
    build:
      context: ./backend
    container_name: BridgePointBackend
    ports:
      - "8000:8000"
    depends_on:
      - database

  database:
    build:
      context: ./database
    container_name: BridgePointDatabase
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: finance_db
      POSTGRES_USER: finance_user
      POSTGRES_PASSWORD: securepassword
    volumes:
      - finance_data:/var/lib/postgresql/data

volumes:
  finance_data: {}